packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  '@swc/core': false
  esbuild: true
  lightningcss: true
  unrs-resolver: false
  '@prisma/client': false
  '@prisma/engines': false
  prisma: false
