/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCompanyRouteImport } from './routes/_app/company'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppInvoicesCreateRouteImport } from './routes/_app/invoices/create'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices/$invoiceId'
import { Route as AppInvoicesInvoiceIdIndexRouteImport } from './routes/_app/invoices/$invoiceId/index'
import { Route as AppInvoicesInvoiceIdEditRouteImport } from './routes/_app/invoices/$invoiceId/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanyRoute = AppCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesCreateRoute = AppInvoicesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesInvoiceIdIndexRoute =
  AppInvoicesInvoiceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInvoicesInvoiceIdRoute,
  } as any)
const AppInvoicesInvoiceIdEditRoute =
  AppInvoicesInvoiceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppInvoicesInvoiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof AppCompanyRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRouteWithChildren
  '/invoices/create': typeof AppInvoicesCreateRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/invoices/$invoiceId/edit': typeof AppInvoicesInvoiceIdEditRoute
  '/invoices/$invoiceId/': typeof AppInvoicesInvoiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof AppCompanyRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/invoices/create': typeof AppInvoicesCreateRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/invoices/$invoiceId/edit': typeof AppInvoicesInvoiceIdEditRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/company': typeof AppCompanyRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/invoices': typeof AppInvoicesRouteWithChildren
  '/_app/products': typeof AppProductsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRouteWithChildren
  '/_app/invoices/create': typeof AppInvoicesCreateRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/invoices/$invoiceId/edit': typeof AppInvoicesInvoiceIdEditRoute
  '/_app/invoices/$invoiceId/': typeof AppInvoicesInvoiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/customers'
    | '/dashboard'
    | '/invoices'
    | '/products'
    | '/profile'
    | '/login'
    | '/register'
    | '/invoices/$invoiceId'
    | '/invoices/create'
    | '/invoices/'
    | '/invoices/$invoiceId/edit'
    | '/invoices/$invoiceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/profile'
    | '/login'
    | '/register'
    | '/invoices/create'
    | '/invoices'
    | '/invoices/$invoiceId/edit'
    | '/invoices/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/company'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/invoices'
    | '/_app/products'
    | '/_app/profile'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/invoices/$invoiceId'
    | '/_app/invoices/create'
    | '/_app/invoices/'
    | '/_app/invoices/$invoiceId/edit'
    | '/_app/invoices/$invoiceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/company': {
      id: '/_app/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AppCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/create': {
      id: '/_app/invoices/create'
      path: '/create'
      fullPath: '/invoices/create'
      preLoaderRoute: typeof AppInvoicesCreateRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/$invoiceId/': {
      id: '/_app/invoices/$invoiceId/'
      path: '/'
      fullPath: '/invoices/$invoiceId/'
      preLoaderRoute: typeof AppInvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof AppInvoicesInvoiceIdRoute
    }
    '/_app/invoices/$invoiceId/edit': {
      id: '/_app/invoices/$invoiceId/edit'
      path: '/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof AppInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof AppInvoicesInvoiceIdRoute
    }
  }
}

interface AppInvoicesInvoiceIdRouteChildren {
  AppInvoicesInvoiceIdEditRoute: typeof AppInvoicesInvoiceIdEditRoute
  AppInvoicesInvoiceIdIndexRoute: typeof AppInvoicesInvoiceIdIndexRoute
}

const AppInvoicesInvoiceIdRouteChildren: AppInvoicesInvoiceIdRouteChildren = {
  AppInvoicesInvoiceIdEditRoute: AppInvoicesInvoiceIdEditRoute,
  AppInvoicesInvoiceIdIndexRoute: AppInvoicesInvoiceIdIndexRoute,
}

const AppInvoicesInvoiceIdRouteWithChildren =
  AppInvoicesInvoiceIdRoute._addFileChildren(AppInvoicesInvoiceIdRouteChildren)

interface AppInvoicesRouteChildren {
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRouteWithChildren
  AppInvoicesCreateRoute: typeof AppInvoicesCreateRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRouteWithChildren,
  AppInvoicesCreateRoute: AppInvoicesCreateRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppRouteChildren {
  AppCompanyRoute: typeof AppCompanyRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompanyRoute: AppCompanyRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
